### ISSUE TITLE
Facebook social features

### ISSUE THREAD

**Issue by thedc89** [nandomoreirame/mug#1]
I wonder how to fix facebook share option.
 Anytime I try to share a post, it ends up this way:
<img width="566" alt="zrzut ekranu 2015-12-24 o 10 29 16" src="https://cloud.githubusercontent.com/assets/4841004/11992694/5ddd76de-aa29-11e5-80f7-9be60f6733d0.png">

Maybe you have an idea how to make it right? I'm aware that facebook made it a bit harder than twitter and one needs to set up an fb app to get it work.

**Comment by nandomoreirame** [comment]
which the url and repo?

**Comment by thedc89** [comment]
Alright, figured it out :)
