### ISSUE TITLE
Symlink error

### ISSUE THREAD

**Issue by nkurapati** [nandomoreirame/mug#2]
Hi,

I am getting following error:

The page build failed with the following error:

A file was included in `source/index.html` that is a symlink or does not exist in your `_includes` directory. For more information, see https://help.github.com/articles/page-build-failed-file-is-a-symlink.

If you have any questions you can contact us by replying to this email.

Please let me know what is the issue.

**Comment by nandomoreirame** [comment]
Github does not accept custom plugins for Jekyll :flushed:

Use the [Rake task](https://github.com/nandomoreirame/mug/blob/master/Rakefile) to build and send to branch gh-pages... 

See this tutorial >> http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html

Thanks!

[nandomoreira-jekyll-theme/issues/2](https://github.com/nandomoreirame/nandomoreira-jekyll-theme/issues/2)

**Comment by ghost** [comment]
Hi,

I have tried using above link. But I am getting 404 error.

This is my repository https://github.com/appgiablog/appgiablog.github.io

Please let me know what is error.

thank you,

**Comment by nandomoreirame** [comment]
Set master to default branch and remove `appgia.com` at CNAME file.

see resolves..

**Comment by ghost** [comment]
Still it gives same error:

 Your site is having problems building: A file was included in source/index.html that is a symlink or does not exist in your _includes directory. For more information, see https://help.github.com/articles/page-build-failed-file-is-a-symlink.

thank you

**Comment by nandomoreirame** [comment]
Github does not accept custom plugins for Jekyll :flushed:

Use the [Rake task](https://github.com/nandomoreirame/mug/blob/master/Rakefile) to build and send to branch gh-pages... 

See this tutorial >> http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html

Thanks!

[nandomoreira-jekyll-theme/issues/2](https://github.com/nandomoreirame/nandomoreira-jekyll-theme/issues/2)
